services:

  nginx:
    container_name: crypto-nginx
    image: nginx:1.23-alpine
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
    ports:
      - 80:80

  php:
    container_name: crypto-php
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./src:/app
  
  database:
    container_name: crypto-database
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306"

  phpmyadmin:
    container_name: crypto-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: unless-stopped
    environment:
        PMA_HOST: database
        PMA_ABSOLUTE_URI: "localhost:80/phpmyadmin/"
    depends_on:
        - database